"""
计算可执行的cdc分数
"""
import os
import json
import math
import re
import sys

#Rule2
def is_code_valid(code):
    """
    Determine if the code is valid.
    """
    try:
        compile(code, '<string>', 'exec')
        return True
    except:
        return False

#Rule3
def is_correct_parameter_count(function_name, correct_code, test_code):
    """
    Check if the number of parameters is consistent.
    """
    pattern = rf'{function_name}\((.*?)\)'
    correct_match = re.search(pattern, correct_code)

    if correct_match:
        correct_params = correct_match.group(1).strip()
        correct_param_list = [p.strip() for p in correct_params.split(',') if p.strip()]
        expected_count = len(correct_param_list)
    else:
        expected_count = 0


    test_match = re.search(pattern, test_code)

    if test_match:
        test_params = test_match.group(1).strip()
        test_param_list = [p.strip() for p in test_params.split(',') if p.strip()]
        return len(test_param_list) == expected_count
    else:

        return expected_count == 0 and function_name in test_code


#Rule5
def check_keyword_parameters(function_name, correct_code, test_code):
    """
    Determine if keyword arguments are correctly used.
    """
    pattern = rf'{function_name}\((.*?)\)'
    correct_match = re.search(pattern, correct_code)

    if correct_match:
        correct_params = correct_match.group(1).strip()
        correct_param_list = [p.strip() for p in correct_params.split(',') if p.strip()]

        test_match = re.search(pattern, test_code)

        if test_match:
            test_params = test_match.group(1).strip()
            test_param_list = [p.strip() for p in test_params.split(',') if p.strip()]

            for correct_param in correct_param_list:
                if '=' in correct_param:
                    param_name = correct_param.split('=')[0].strip()
                    if not any(param_name in test_param and '=' in test_param for test_param in test_param_list):
                        return False

            return True

    return False

#Rule4
def with_correct(answer_code:str, model_output:str)->bool:
    """
    When the ground truth involves a with statement,
    determine whether the code generated by the model uses a with statement.
    """
    if not answer_code.startswith('with') and not model_output.startswith('with'):
        return True
    elif answer_code.startswith('with') and model_output.startswith('with'):
        return True
    else:
        return False

def compute_line_score_k(answer:str, model_output:list, k:int, model_filled_code, core_line):

    c = 0
    n = len(model_output)
    for index, code in enumerate(model_output):
        # if re.search(rf'\b{re.escape(answer)}\b', code) and is_code_valid(model_filled_code[str(index + 1)]) == True:#line

        if re.search(rf'\b{re.escape(answer)}\b', code) and is_code_valid(model_filled_code[str(index + 1)]) and is_correct_parameter_count(answer, core_line, code) and with_correct(core_line, code) and check_keyword_parameters(answer, core_line, code):#line
        #     print(f"字符串匹配通过但编译不通过的行：\n"
        #           f"core_token:\t{answer}\n"
        #           f"core_line:\t{core_line}\n"
        #           f"model_output:\t{code}")
        #     print("=====================================")
            c += 1
    if n-c < k:
        return 1.0

    score = 1 - (math.comb(n - c, k))/(math.comb(n, k))

    return score

def compute_block_score_k(answer:str, model_output:list, k:int, core_line_in_core_block, core_line_in_output_clear):

    c = 0
    n = len(model_output)
    for index, code in enumerate(model_output):
        if re.search(rf'\b{re.escape(answer)}\b', code) and is_code_valid(code) and is_correct_parameter_count(answer, core_line_in_core_block, core_line_in_output_clear[index]) and with_correct(core_line_in_core_block, core_line_in_output_clear[index]) and check_keyword_parameters(answer, core_line_in_core_block, core_line_in_output_clear[index]):#block
        #     try:
        #         print(f"data id:\t{data_id}\n")
        #         print(f"字符串匹配通过但编译不通过的行：\n"
        #               f"pass rate:\t{test_results[str(index + 1)]['pass_rate']}\n"
        #               f"core_token:\t{answer}\n"
        #               f"core_line:\t{core_line_in_core_block}\n"
        #               f"model_output:\t{core_line_in_output_clear[index]}")
        #         print("=====================================")
        #     except:
        #         pass
            c += 1
    if n-c < k:
        return 1.0

    score = 1 - (math.comb(n - c, k))/(math.comb(n, k))

    return score

#Rule 1
def compute_block_pass_k(answer:str, model_output:list, k:int):

    c = 0
    n = len(model_output)
    for index, code in enumerate(model_output):
        if re.search(rf'\b{re.escape(answer)}\b', code):#block
        #     try:
        #         print(f"data id:\t{data_id}\n")
        #         print(f"字符串匹配通过但编译不通过的行：\n"
        #               f"pass rate:\t{test_results[str(index + 1)]['pass_rate']}\n"
        #               f"core_token:\t{answer}\n"
        #               f"core_line:\t{core_line_in_core_block}\n"
        #               f"model_output:\t{core_line_in_output_clear[index]}")
        #         print("=====================================")
        #     except:
        #         pass
            c += 1
    if n-c < k:
        return 1.0

    score = 1 - (math.comb(n - c, k))/(math.comb(n, k))

    return score

k = 1   #em@k
task = "block"
# json_name = f'test_data_{task}_with_complete_import_temp.json'#有import block
# json_name = f'test_data_{task}_with_complete_import.json'#有import line
# json_name = f'test_data_{task}_without_import.json'#无import line
# json_name = f'test_data_{task}_without_import_v2_temp.json'#无import block
# json_name = f'test_data_{task}_with_complete_import_without_version_temp.json'#有import block without version
# json_name = f'test_data_{task}_with_complete_import_without_version.json'#有import line without version
# json_name = f'test_data_{task}_without_import_without_version_temp.json'#无import block without version
# json_name = f'test_data_{task}_without_import_without_version.json'#无import line without version
# json_name = f'old_to_new_graph_200_temp.json'

# # folder_path = f'../../dataset/final_dataset/execute_dataset_without_import_without_version'
# folder_path = f'../../executable versicode/datasets/'
# model_list = os.listdir(folder_path)

# for model in model_list:
model = 'Llama3-70B'
# model_json_path = os.path.join(folder_path, model, json_name)

model_json_path = sys.argv[1]
with open(model_json_path, 'r', encoding='utf-8')as fr:
    lodict = json.load(fr)
data_list = lodict['data']



if task == 'line':
    score_list = []
    for data in data_list:
        # model_output_list = eval(data['model_output_clear'])  # change block or token or line
        model_output_list = data['model_output_clear']  # change block or token or line
        temp_list = []
        for o in model_output_list:
            temp_out = o.replace('```python', '')
            temp_out = temp_out.replace('```', '')
            temp_list.append(temp_out)
        model_output = temp_list
        answer = data['core_token']
        # model_output = data['model_output_clear']
        model_filled_code = data['model_filled_code']
        core_line = data['core_line']
        score_list.append(compute_line_score_k(answer, model_output, k, model_filled_code, core_line))
        # score_list.append(compute_score_k(answer, model_output, k, model_filled_code, test_results, core_line, core_line_in_core_block, core_line_in_output_clear))

    final_score = sum(score_list)/len(score_list)
    print(f"{model}的{task}的cdc@{k}为\t{final_score}")

elif task == 'block':
    score_list = []
    score_list_3 = []
    score_p_list = []
    for data in data_list:
        # answer = data['core_token']
        if "old_to_new" in sys.argv[1]:
            answer = data['new_name']
        elif "new_to_old" in sys.argv[1]:
            answer = data['old_name']
        elif "minor" or "major" in sys.argv[1]:
            answer = data['new_name']
        else:
            answer = data['answer']

        # model_output_list = eval(data['model_output_clear'])  # change block or token or line
        model_output_list = data['model_output_clear'] # change block or token or line

        temp_list = []
        for o in model_output_list:
            temp_out = o.replace('```python', '')
            temp_out = temp_out.replace('```', '')
            temp_list.append(temp_out)
        model_output = temp_list
        # model_filled_code = data['model_filled_code']
        core_line_in_core_block = data['core_line_in_core_block']
        core_line_in_output_clear = data['core_line_in_output_clear']
        score_list.append(compute_block_score_k(answer, model_output, k, core_line_in_core_block, core_line_in_output_clear))
        # compute cdc@3
        score_list_3.append(compute_block_score_k(answer, model_output, 3, core_line_in_core_block, core_line_in_output_clear))
        score_p_list.append(compute_block_pass_k(answer, model_output, k))

    final_score = sum(score_list) / len(score_list)
    pass_k_socre = sum(score_p_list) / len(score_list)
    final_score_3 = sum(score_list_3) / len(score_list_3)

    print(f"{model}的{task}的cdc@{k}为\t{final_score}")
    print(f"{model}的{task}的cdc@{3}为\t{final_score_3}")
    print(f"{model}的{task}的em@{k}为\t{pass_k_socre}")
    # break
